#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AbilityTooltip_HoneyDew_Fist

#include "Basic.hpp"

#include "HUD_AbilityInteractionContext_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AbilityTooltip_HoneyDew_Fist.AbilityTooltip_HoneyDew_Fist_C
// 0x0000 (0x0400 - 0x0400)
class UAbilityTooltip_HoneyDew_Fist_C final : public UHUD_AbilityInteractionContext_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AbilityTooltip_HoneyDew_Fist_C">();
	}
	static class UAbilityTooltip_HoneyDew_Fist_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityTooltip_HoneyDew_Fist_C>();
	}
};
static_assert(alignof(UAbilityTooltip_HoneyDew_Fist_C) == 0x000008, "Wrong alignment on UAbilityTooltip_HoneyDew_Fist_C");
static_assert(sizeof(UAbilityTooltip_HoneyDew_Fist_C) == 0x000400, "Wrong size on UAbilityTooltip_HoneyDew_Fist_C");

}

