#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Hightower_HoneyDew_Fist

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PhysicsCore_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function B_Hightower_HoneyDew_Fist.B_Hightower_HoneyDew_Fist_C.ExecuteUbergraph_B_Hightower_HoneyDew_Fist
// 0x0DF0 (0x0DF0 - 0x0000)
struct B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue_1;          // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_Event_HitResult;                            // 0x0008(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	EPhysicalSurface                              K2Node_Event_ImpactPhysicalSurface;                // 0x0094(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_95[0x3];                                       // 0x0095(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UFXSystemComponent*                     K2Node_Event_SpawnedPSC;                           // 0x0098(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A2[0x2];                                       // 0x00A2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x00AC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x00B8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x00C4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x00D0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x00F0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x010C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0118(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_Conv_VectorToRotator_ReturnValue;         // 0x0124(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_RandomRotator_ReturnValue;                // 0x0130(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_13C[0x4];                                      // 0x013C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UDecalComponent*                        CallFunc_SpawnDecalAtLocation_ReturnValue;         // 0x0140(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x014C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0154(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_AddLocalRotation_SweepHitResult;       // 0x0160(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue_2;          // 0x01EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1ED[0x3];                                      // 0x01ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetInstigator_ReturnValue;                // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPawn*                              K2Node_DynamicCast_AsFort_Pawn;                    // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0201(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x0202(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue_1;       // 0x0203(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetRelativeLocationAndRotation_SweepHitResult; // 0x0204(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeLocationAndRotation_SweepHitResult_1; // 0x0290(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue_3;          // 0x031C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue_4;          // 0x031D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bVisible;                             // 0x031E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bSetForLocalControllerOnly;           // 0x031F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue_2;       // 0x0320(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_321[0x3];                                      // 0x0321(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_AddWorldOffset_SweepHitResult;         // 0x0324(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue;       // 0x03B0(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue_1;     // 0x03E0(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0410(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x041C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0428(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location_1;                // 0x0434(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation_1;                // 0x0440(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale_1;                   // 0x044C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_458[0x8];                                      // 0x0458(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0460(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue_1;              // 0x0490(0x0030)(IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldTransform_SweepHitResult;      // 0x04C0(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_AddLocalRotation_SweepHitResult_1;     // 0x054C(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_AddWorldOffset_SweepHitResult_1;       // 0x05D8(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_AddLocalRotation_SweepHitResult_2;     // 0x0664(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_AddWorldOffset_SweepHitResult_2;       // 0x06F0(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_AddLocalRotation_SweepHitResult_3;     // 0x077C(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetWorldTransform_SweepHitResult_1;    // 0x0808(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_AddWorldOffset_SweepHitResult_3;       // 0x0894(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue_2;     // 0x0920(0x0030)(IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_AddLocalRotation_SweepHitResult_4;     // 0x0950(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                CallFunc_BreakTransform_Location_2;                // 0x09DC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation_2;                // 0x09E8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale_2;                   // 0x09F4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue_2;              // 0x0A00(0x0030)(IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldTransform_SweepHitResult_2;    // 0x0A30(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         Pad_ABC[0x4];                                      // 0x0ABC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue_3;     // 0x0AC0(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Location_3;                // 0x0AF0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation_3;                // 0x0AFC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale_3;                   // 0x0B08(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0B14(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue_3;              // 0x0B20(0x0030)(IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldTransform_SweepHitResult_3;    // 0x0B50(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         Pad_BDC[0x4];                                      // 0x0BDC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x0BE0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EGameplayCueEvent                             K2Node_GameplayCueEvent_EventType_1;               // 0x0BE8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BE9[0x7];                                      // 0x0BE9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayCueParameters                 K2Node_GameplayCueEvent_Parameters_1;              // 0x0BF0(0x00B8)(ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_AddLocalOffset_SweepHitResult;         // 0x0CA8(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	EGameplayCueEvent                             K2Node_GameplayCueEvent_EventType;                 // 0x0D34(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D35[0x3];                                      // 0x0D35(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayCueParameters                 K2Node_GameplayCueEvent_Parameters;                // 0x0D38(0x00B8)(ContainsInstancedReference)
};
static_assert(alignof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist) == 0x000010, "Wrong alignment on B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist");
static_assert(sizeof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist) == 0x000DF0, "Wrong size on B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, EntryPoint) == 0x000000, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::EntryPoint' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_IsDedicatedServer_ReturnValue) == 0x000004, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_IsDedicatedServer_ReturnValue_1) == 0x000005, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_IsDedicatedServer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, K2Node_Event_HitResult) == 0x000008, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::K2Node_Event_HitResult' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, K2Node_Event_ImpactPhysicalSurface) == 0x000094, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::K2Node_Event_ImpactPhysicalSurface' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, K2Node_Event_SpawnedPSC) == 0x000098, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::K2Node_Event_SpawnedPSC' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_bBlockingHit) == 0x0000A0, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_bInitialOverlap) == 0x0000A1, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_Time) == 0x0000A4, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_Distance) == 0x0000A8, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_Location) == 0x0000AC, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_ImpactPoint) == 0x0000B8, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_Normal) == 0x0000C4, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_ImpactNormal) == 0x0000D0, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_PhysMat) == 0x0000E0, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_HitActor) == 0x0000E8, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_HitComponent) == 0x0000F0, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_HitBoneName) == 0x0000F8, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_HitItem) == 0x000100, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_ElementIndex) == 0x000104, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_FaceIndex) == 0x000108, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_TraceStart) == 0x00010C, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakHitResult_TraceEnd) == 0x000118, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_Conv_VectorToRotator_ReturnValue) == 0x000124, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_Conv_VectorToRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_RandomRotator_ReturnValue) == 0x000130, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_RandomRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_SpawnDecalAtLocation_ReturnValue) == 0x000140, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_SpawnDecalAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakRotator_Roll) == 0x000148, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakRotator_Pitch) == 0x00014C, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakRotator_Yaw) == 0x000150, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_MakeRotator_ReturnValue) == 0x000154, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_AddLocalRotation_SweepHitResult) == 0x000160, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_AddLocalRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_IsDedicatedServer_ReturnValue_2) == 0x0001EC, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_IsDedicatedServer_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_GetInstigator_ReturnValue) == 0x0001F0, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_GetInstigator_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, K2Node_DynamicCast_AsFort_Pawn) == 0x0001F8, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::K2Node_DynamicCast_AsFort_Pawn' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, K2Node_DynamicCast_bSuccess) == 0x000200, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_IsValid_ReturnValue) == 0x000201, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_AttachToComponent_ReturnValue) == 0x000202, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_AttachToComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_AttachToComponent_ReturnValue_1) == 0x000203, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_AttachToComponent_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_SetRelativeLocationAndRotation_SweepHitResult) == 0x000204, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_SetRelativeLocationAndRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_SetRelativeLocationAndRotation_SweepHitResult_1) == 0x000290, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_SetRelativeLocationAndRotation_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_IsDedicatedServer_ReturnValue_3) == 0x00031C, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_IsDedicatedServer_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_IsDedicatedServer_ReturnValue_4) == 0x00031D, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_IsDedicatedServer_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, K2Node_Event_bVisible) == 0x00031E, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::K2Node_Event_bVisible' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, K2Node_Event_bSetForLocalControllerOnly) == 0x00031F, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::K2Node_Event_bSetForLocalControllerOnly' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_AttachToComponent_ReturnValue_2) == 0x000320, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_AttachToComponent_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_AddWorldOffset_SweepHitResult) == 0x000324, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_AddWorldOffset_SweepHitResult' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_GetComponentToWorld_ReturnValue) == 0x0003B0, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_GetComponentToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_GetComponentToWorld_ReturnValue_1) == 0x0003E0, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_GetComponentToWorld_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakTransform_Location) == 0x000410, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakTransform_Rotation) == 0x00041C, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakTransform_Scale) == 0x000428, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakTransform_Location_1) == 0x000434, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakTransform_Location_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakTransform_Rotation_1) == 0x000440, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakTransform_Rotation_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakTransform_Scale_1) == 0x00044C, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakTransform_Scale_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_MakeTransform_ReturnValue) == 0x000460, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_MakeTransform_ReturnValue_1) == 0x000490, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_MakeTransform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_SetWorldTransform_SweepHitResult) == 0x0004C0, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_SetWorldTransform_SweepHitResult' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_AddLocalRotation_SweepHitResult_1) == 0x00054C, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_AddLocalRotation_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_AddWorldOffset_SweepHitResult_1) == 0x0005D8, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_AddWorldOffset_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_AddLocalRotation_SweepHitResult_2) == 0x000664, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_AddLocalRotation_SweepHitResult_2' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_AddWorldOffset_SweepHitResult_2) == 0x0006F0, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_AddWorldOffset_SweepHitResult_2' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_AddLocalRotation_SweepHitResult_3) == 0x00077C, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_AddLocalRotation_SweepHitResult_3' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_SetWorldTransform_SweepHitResult_1) == 0x000808, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_SetWorldTransform_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_AddWorldOffset_SweepHitResult_3) == 0x000894, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_AddWorldOffset_SweepHitResult_3' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_GetComponentToWorld_ReturnValue_2) == 0x000920, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_GetComponentToWorld_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_AddLocalRotation_SweepHitResult_4) == 0x000950, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_AddLocalRotation_SweepHitResult_4' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakTransform_Location_2) == 0x0009DC, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakTransform_Location_2' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakTransform_Rotation_2) == 0x0009E8, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakTransform_Rotation_2' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakTransform_Scale_2) == 0x0009F4, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakTransform_Scale_2' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_MakeTransform_ReturnValue_2) == 0x000A00, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_MakeTransform_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_SetWorldTransform_SweepHitResult_2) == 0x000A30, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_SetWorldTransform_SweepHitResult_2' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_GetComponentToWorld_ReturnValue_3) == 0x000AC0, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_GetComponentToWorld_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakTransform_Location_3) == 0x000AF0, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakTransform_Location_3' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakTransform_Rotation_3) == 0x000AFC, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakTransform_Rotation_3' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_BreakTransform_Scale_3) == 0x000B08, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_BreakTransform_Scale_3' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000B14, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_MakeTransform_ReturnValue_3) == 0x000B20, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_MakeTransform_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_SetWorldTransform_SweepHitResult_3) == 0x000B50, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_SetWorldTransform_SweepHitResult_3' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x000BE0, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, K2Node_GameplayCueEvent_EventType_1) == 0x000BE8, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::K2Node_GameplayCueEvent_EventType_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, K2Node_GameplayCueEvent_Parameters_1) == 0x000BF0, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::K2Node_GameplayCueEvent_Parameters_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, CallFunc_K2_AddLocalOffset_SweepHitResult) == 0x000CA8, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::CallFunc_K2_AddLocalOffset_SweepHitResult' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, K2Node_GameplayCueEvent_EventType) == 0x000D34, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::K2Node_GameplayCueEvent_EventType' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist, K2Node_GameplayCueEvent_Parameters) == 0x000D38, "Member 'B_Hightower_HoneyDew_Fist_C_ExecuteUbergraph_B_Hightower_HoneyDew_Fist::K2Node_GameplayCueEvent_Parameters' has a wrong offset!");

// Function B_Hightower_HoneyDew_Fist.B_Hightower_HoneyDew_Fist_C.GameplayCue.HighTower.HoneyDew.Fist.Swing4
// 0x00C0 (0x00C0 - 0x0000)
struct B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Swing4 final
{
public:
	EGameplayCueEvent                             EventType;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)
};
static_assert(alignof(B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Swing4) == 0x000008, "Wrong alignment on B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Swing4");
static_assert(sizeof(B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Swing4) == 0x0000C0, "Wrong size on B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Swing4");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Swing4, EventType) == 0x000000, "Member 'B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Swing4::EventType' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Swing4, Parameters) == 0x000008, "Member 'B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Swing4::Parameters' has a wrong offset!");

// Function B_Hightower_HoneyDew_Fist.B_Hightower_HoneyDew_Fist_C.GameplayCue.HighTower.HoneyDew.Fist.Smash
// 0x00C0 (0x00C0 - 0x0000)
struct B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Smash final
{
public:
	EGameplayCueEvent                             EventType;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)
};
static_assert(alignof(B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Smash) == 0x000008, "Wrong alignment on B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Smash");
static_assert(sizeof(B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Smash) == 0x0000C0, "Wrong size on B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Smash");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Smash, EventType) == 0x000000, "Member 'B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Smash::EventType' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Smash, Parameters) == 0x000008, "Member 'B_Hightower_HoneyDew_Fist_C_GameplayCue_HighTower_HoneyDew_Fist_Smash::Parameters' has a wrong offset!");

// Function B_Hightower_HoneyDew_Fist.B_Hightower_HoneyDew_Fist_C.OnWeaponVisibilityChanged
// 0x0002 (0x0002 - 0x0000)
struct B_Hightower_HoneyDew_Fist_C_OnWeaponVisibilityChanged final
{
public:
	bool                                          bVisible;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bSetForLocalControllerOnly;                        // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(B_Hightower_HoneyDew_Fist_C_OnWeaponVisibilityChanged) == 0x000001, "Wrong alignment on B_Hightower_HoneyDew_Fist_C_OnWeaponVisibilityChanged");
static_assert(sizeof(B_Hightower_HoneyDew_Fist_C_OnWeaponVisibilityChanged) == 0x000002, "Wrong size on B_Hightower_HoneyDew_Fist_C_OnWeaponVisibilityChanged");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_OnWeaponVisibilityChanged, bVisible) == 0x000000, "Member 'B_Hightower_HoneyDew_Fist_C_OnWeaponVisibilityChanged::bVisible' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_OnWeaponVisibilityChanged, bSetForLocalControllerOnly) == 0x000001, "Member 'B_Hightower_HoneyDew_Fist_C_OnWeaponVisibilityChanged::bSetForLocalControllerOnly' has a wrong offset!");

// Function B_Hightower_HoneyDew_Fist.B_Hightower_HoneyDew_Fist_C.OnPlayImpactFX
// 0x0098 (0x0098 - 0x0000)
struct B_Hightower_HoneyDew_Fist_C_OnPlayImpactFX final
{
public:
	struct FHitResult                             HitResult;                                         // 0x0000(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	EPhysicalSurface                              ImpactPhysicalSurface;                             // 0x008C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8D[0x3];                                       // 0x008D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UFXSystemComponent*                     SpawnedPSC;                                        // 0x0090(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Hightower_HoneyDew_Fist_C_OnPlayImpactFX) == 0x000008, "Wrong alignment on B_Hightower_HoneyDew_Fist_C_OnPlayImpactFX");
static_assert(sizeof(B_Hightower_HoneyDew_Fist_C_OnPlayImpactFX) == 0x000098, "Wrong size on B_Hightower_HoneyDew_Fist_C_OnPlayImpactFX");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_OnPlayImpactFX, HitResult) == 0x000000, "Member 'B_Hightower_HoneyDew_Fist_C_OnPlayImpactFX::HitResult' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_OnPlayImpactFX, ImpactPhysicalSurface) == 0x00008C, "Member 'B_Hightower_HoneyDew_Fist_C_OnPlayImpactFX::ImpactPhysicalSurface' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_OnPlayImpactFX, SpawnedPSC) == 0x000090, "Member 'B_Hightower_HoneyDew_Fist_C_OnPlayImpactFX::SpawnedPSC' has a wrong offset!");

// Function B_Hightower_HoneyDew_Fist.B_Hightower_HoneyDew_Fist_C.BindDualMeleeSwingEvents
// 0x0118 (0x0118 - 0x0000)
struct B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents final
{
public:
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0000(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0020(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0030(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x0040(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x0050(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_6;            // 0x0060(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_7;            // 0x0070(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_8;            // 0x0080(0x0010)(ZeroConstructor, NoDestructor)
	class APawn*                                  CallFunc_GetInstigator_ReturnValue;                // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_9;            // 0x0098(0x0010)(ZeroConstructor, NoDestructor)
	class APlayerPawn_Athena_C*                   K2Node_DynamicCast_AsPlayer_Pawn_Athena;           // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B1[0x3];                                       // 0x00B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_10;           // 0x00B4(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_11;           // 0x00C4(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_D4[0x4];                                       // 0x00D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetInstigator_ReturnValue_1;              // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_GetInstigator_ReturnValue_2;              // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ObjectToString_ReturnValue;          // 0x00E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class APlayerPawn_Generic_C*                  K2Node_DynamicCast_AsPlayer_Pawn_Generic;          // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0108(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents) == 0x000008, "Wrong alignment on B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents");
static_assert(sizeof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents) == 0x000118, "Wrong size on B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_CreateDelegate_OutputDelegate) == 0x000000, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_CreateDelegate_OutputDelegate_1) == 0x000010, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_CreateDelegate_OutputDelegate_2) == 0x000020, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_CreateDelegate_OutputDelegate_3) == 0x000030, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_CreateDelegate_OutputDelegate_4) == 0x000040, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_CreateDelegate_OutputDelegate_5) == 0x000050, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_CreateDelegate_OutputDelegate_6) == 0x000060, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_CreateDelegate_OutputDelegate_7) == 0x000070, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_CreateDelegate_OutputDelegate_8) == 0x000080, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_CreateDelegate_OutputDelegate_8' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, CallFunc_GetInstigator_ReturnValue) == 0x000090, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::CallFunc_GetInstigator_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_CreateDelegate_OutputDelegate_9) == 0x000098, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_CreateDelegate_OutputDelegate_9' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_DynamicCast_AsPlayer_Pawn_Athena) == 0x0000A8, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_DynamicCast_AsPlayer_Pawn_Athena' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_DynamicCast_bSuccess) == 0x0000B0, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_CreateDelegate_OutputDelegate_10) == 0x0000B4, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_CreateDelegate_OutputDelegate_10' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_CreateDelegate_OutputDelegate_11) == 0x0000C4, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_CreateDelegate_OutputDelegate_11' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, CallFunc_GetInstigator_ReturnValue_1) == 0x0000D8, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::CallFunc_GetInstigator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, CallFunc_GetInstigator_ReturnValue_2) == 0x0000E0, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::CallFunc_GetInstigator_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, CallFunc_Conv_ObjectToString_ReturnValue) == 0x0000E8, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::CallFunc_Conv_ObjectToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_DynamicCast_AsPlayer_Pawn_Generic) == 0x0000F8, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_DynamicCast_AsPlayer_Pawn_Generic' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, K2Node_DynamicCast_bSuccess_1) == 0x000100, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents, CallFunc_Concat_StrStr_ReturnValue) == 0x000108, "Member 'B_Hightower_HoneyDew_Fist_C_BindDualMeleeSwingEvents::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");

}

