#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BB_ArsenicDash

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BB_ArsenicDash.BB_ArsenicDash_C
// 0x0000 (0x00B0 - 0x00B0)
class UBB_ArsenicDash_C final : public UFortMobileActionButtonBehavior
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BB_ArsenicDash_C">();
	}
	static class UBB_ArsenicDash_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBB_ArsenicDash_C>();
	}
};
static_assert(alignof(UBB_ArsenicDash_C) == 0x000008, "Wrong alignment on UBB_ArsenicDash_C");
static_assert(sizeof(UBB_ArsenicDash_C) == 0x0000B0, "Wrong size on UBB_ArsenicDash_C");

}

