#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BB_ArsenicScream

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BB_ArsenicScream.BB_ArsenicScream_C
// 0x0000 (0x00B0 - 0x00B0)
class UBB_ArsenicScream_C final : public UFortMobileActionButtonBehavior
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BB_ArsenicScream_C">();
	}
	static class UBB_ArsenicScream_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBB_ArsenicScream_C>();
	}
};
static_assert(alignof(UBB_ArsenicScream_C) == 0x000008, "Wrong alignment on UBB_ArsenicScream_C");
static_assert(sizeof(UBB_ArsenicScream_C) == 0x0000B0, "Wrong size on UBB_ArsenicScream_C");

}

