#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_ArsenicCore_Claws

#include "Basic.hpp"

#include "GA_Hightower_Wasabi_Claws_Mantis_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_ArsenicCore_Claws.GA_ArsenicCore_Claws_C
// 0x0000 (0x0B38 - 0x0B38)
class UGA_ArsenicCore_Claws_C final : public UGA_Hightower_Wasabi_Claws_Mantis_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_ArsenicCore_Claws_C">();
	}
	static class UGA_ArsenicCore_Claws_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_ArsenicCore_Claws_C>();
	}
};
static_assert(alignof(UGA_ArsenicCore_Claws_C) == 0x000008, "Wrong alignment on UGA_ArsenicCore_Claws_C");
static_assert(sizeof(UGA_ArsenicCore_Claws_C) == 0x000B38, "Wrong size on UGA_ArsenicCore_Claws_C");

}

