#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_HighTower_Tapas_SkyStrike_Fire

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK::Params
{

// Function GA_HighTower_Tapas_SkyStrike_Fire.GA_HighTower_Tapas_SkyStrike_Fire_C.ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire
// 0x0390 (0x0390 - 0x0000)
struct GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	struct FGameplayTag                           K2Node_Event_NotifyTag;                            // 0x0014(0x0008)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFortGameplayEffectContainerSpec       CallFunc_MakeGameplayEffectContainerSpec_ReturnValue; // 0x0020(0x00B8)()
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x00D8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Normal_ReturnValue;                       // 0x00E4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotFromX_ReturnValue;                 // 0x00F0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x00FC(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_EqualEqual_GameplayTag_ReturnValue;       // 0x010C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_10D[0x3];                                      // 0x010D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0110(0x0008)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetValueAtLevel_ReturnValue;              // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortProjectileBase*                    CallFunc_SpawnProjectile_ReturnValue;              // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerController*                  CallFunc_GetFortPlayerControllerFromActor_ReturnValue; // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bWasCancelled;                        // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_131[0xF];                                      // 0x0131(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0140(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetAimedAtPoint_OutHit_Location;          // 0x0178(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_184[0x4];                                      // 0x0184(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_SkyStrike_AimIndicator_C*           CallFunc_FinishSpawningActor_ReturnValue;          // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult;       // 0x0190(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue;          // 0x021C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_HasAuthority_ReturnValue;              // 0x021D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x021E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x021F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TArray<class AWorldSettings*>                 CallFunc_GetAllActorsOfClass_OutActors;            // 0x0220(0x0010)(ReferenceParm, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue_1;                   // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_231[0x7];                                      // 0x0231(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AWorldSettings*                         CallFunc_Array_Get_Item;                           // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue;  // 0x0240(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0248(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_254[0x4];                                      // 0x0254(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayCueParameters                 CallFunc_MakeGameplayCueParameters_ReturnValue;    // 0x0258(0x00B8)(ContainsInstancedReference)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_1;        // 0x0310(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_314[0x4];                                      // 0x0314(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEffectSpecHandle              CallFunc_MakeOutgoingGameplayEffectSpec_ReturnValue; // 0x0318(0x0010)()
	struct FGameplayEffectSpecHandle              CallFunc_AssignTagSetByCallerMagnitude_ReturnValue; // 0x0328(0x0010)()
	struct FGameplayEffectSpecHandle              CallFunc_AssignTagSetByCallerMagnitude_ReturnValue_1; // 0x0338(0x0010)()
	struct FActiveGameplayEffectHandle            CallFunc_K2_ApplyGameplayEffectSpecToOwner_ReturnValue; // 0x0348(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_1;        // 0x0350(0x0008)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0358(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x035C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0360(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_RowToBool_ReturnValue;                    // 0x0364(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_365[0x3];                                      // 0x0365(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_FMin_ReturnValue;                         // 0x0368(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetValueAtLevel_ReturnValue_1;            // 0x036C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0370(0x0010)(ZeroConstructor, NoDestructor)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_2;        // 0x0380(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire) == 0x000010, "Wrong alignment on GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire");
static_assert(sizeof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire) == 0x000390, "Wrong size on GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, EntryPoint) == 0x000000, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, K2Node_Event_NotifyTag) == 0x000014, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::K2Node_Event_NotifyTag' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_MakeGameplayEffectContainerSpec_ReturnValue) == 0x000020, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_MakeGameplayEffectContainerSpec_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_Subtract_VectorVector_ReturnValue) == 0x0000D8, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_Normal_ReturnValue) == 0x0000E4, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_Normal_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_MakeRotFromX_ReturnValue) == 0x0000F0, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_MakeRotFromX_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000FC, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_EqualEqual_GameplayTag_ReturnValue) == 0x00010C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_EqualEqual_GameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000110, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000118, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_GetValueAtLevel_ReturnValue) == 0x00011C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_GetValueAtLevel_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_SpawnProjectile_ReturnValue) == 0x000120, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_SpawnProjectile_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_GetFortPlayerControllerFromActor_ReturnValue) == 0x000128, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_GetFortPlayerControllerFromActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, K2Node_Event_bWasCancelled) == 0x000130, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::K2Node_Event_bWasCancelled' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_MakeTransform_ReturnValue) == 0x000140, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000170, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_GetAimedAtPoint_OutHit_Location) == 0x000178, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_GetAimedAtPoint_OutHit_Location' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_FinishSpawningActor_ReturnValue) == 0x000188, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_K2_SetActorLocation_SweepHitResult) == 0x000190, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_K2_SetActorLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_K2_SetActorLocation_ReturnValue) == 0x00021C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_K2_SetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_K2_HasAuthority_ReturnValue) == 0x00021D, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_K2_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_IsValid_ReturnValue) == 0x00021E, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_IsServer_ReturnValue) == 0x00021F, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_IsServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_GetAllActorsOfClass_OutActors) == 0x000220, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_IsServer_ReturnValue_1) == 0x000230, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_IsServer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_Array_Get_Item) == 0x000238, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_GetOwningActorFromActorInfo_ReturnValue) == 0x000240, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_GetOwningActorFromActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000248, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_MakeGameplayCueParameters_ReturnValue) == 0x000258, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_MakeGameplayCueParameters_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_Subtract_FloatFloat_ReturnValue_1) == 0x000310, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_Subtract_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_MakeOutgoingGameplayEffectSpec_ReturnValue) == 0x000318, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_MakeOutgoingGameplayEffectSpec_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_AssignTagSetByCallerMagnitude_ReturnValue) == 0x000328, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_AssignTagSetByCallerMagnitude_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_AssignTagSetByCallerMagnitude_ReturnValue_1) == 0x000338, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_AssignTagSetByCallerMagnitude_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_K2_ApplyGameplayEffectSpecToOwner_ReturnValue) == 0x000348, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_K2_ApplyGameplayEffectSpecToOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_K2_SetTimerDelegate_ReturnValue_1) == 0x000350, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_K2_SetTimerDelegate_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000358, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x00035C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_Add_FloatFloat_ReturnValue) == 0x000360, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_RowToBool_ReturnValue) == 0x000364, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_RowToBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_FMin_ReturnValue) == 0x000368, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_FMin_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_GetValueAtLevel_ReturnValue_1) == 0x00036C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_GetValueAtLevel_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, K2Node_CreateDelegate_OutputDelegate_2) == 0x000370, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire, CallFunc_K2_SetTimerDelegate_ReturnValue_2) == 0x000380, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_ExecuteUbergraph_GA_HighTower_Tapas_SkyStrike_Fire::CallFunc_K2_SetTimerDelegate_ReturnValue_2' has a wrong offset!");

// Function GA_HighTower_Tapas_SkyStrike_Fire.GA_HighTower_Tapas_SkyStrike_Fire_C.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct GA_HighTower_Tapas_SkyStrike_Fire_C_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_HighTower_Tapas_SkyStrike_Fire_C_K2_OnEndAbility) == 0x000001, "Wrong alignment on GA_HighTower_Tapas_SkyStrike_Fire_C_K2_OnEndAbility");
static_assert(sizeof(GA_HighTower_Tapas_SkyStrike_Fire_C_K2_OnEndAbility) == 0x000001, "Wrong size on GA_HighTower_Tapas_SkyStrike_Fire_C_K2_OnEndAbility");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

// Function GA_HighTower_Tapas_SkyStrike_Fire.GA_HighTower_Tapas_SkyStrike_Fire_C.CastMontageNotifyStart
// 0x0008 (0x0008 - 0x0000)
struct GA_HighTower_Tapas_SkyStrike_Fire_C_CastMontageNotifyStart final
{
public:
	struct FGameplayTag                           NotifyTag;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_HighTower_Tapas_SkyStrike_Fire_C_CastMontageNotifyStart) == 0x000004, "Wrong alignment on GA_HighTower_Tapas_SkyStrike_Fire_C_CastMontageNotifyStart");
static_assert(sizeof(GA_HighTower_Tapas_SkyStrike_Fire_C_CastMontageNotifyStart) == 0x000008, "Wrong size on GA_HighTower_Tapas_SkyStrike_Fire_C_CastMontageNotifyStart");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_CastMontageNotifyStart, NotifyTag) == 0x000000, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_CastMontageNotifyStart::NotifyTag' has a wrong offset!");

// Function GA_HighTower_Tapas_SkyStrike_Fire.GA_HighTower_Tapas_SkyStrike_Fire_C.FindHammerPath
// 0x0218 (0x0218 - 0x0000)
struct GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayCueParameters                 CallFunc_MakeGameplayCueParameters_ReturnValue;    // 0x0008(0x00B8)(ContainsInstancedReference)
	struct FVector                                CallFunc_GetAimedAtPoint_OutHit_Location;          // 0x00C0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CC[0x4];                                       // 0x00CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x00D0(0x0010)(ConstParm, ReferenceParm, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x00E0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x00EC(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0179(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x017A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_17B[0x1];                                      // 0x017B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x017C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0180(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x0184(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0190(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x019C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x01A8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B4[0x4];                                      // 0x01B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x01B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x01C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x01DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x01E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x01E4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x01F0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_Select_Default;                             // 0x01FC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue_1;           // 0x0208(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath) == 0x000008, "Wrong alignment on GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath");
static_assert(sizeof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath) == 0x000218, "Wrong size on GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, Temp_bool_Variable) == 0x000000, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_MakeGameplayCueParameters_ReturnValue) == 0x000008, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_MakeGameplayCueParameters_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_GetAimedAtPoint_OutHit_Location) == 0x0000C0, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_GetAimedAtPoint_OutHit_Location' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, Temp_object_Variable) == 0x0000D0, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_Add_VectorVector_ReturnValue) == 0x0000E0, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_LineTraceSingle_OutHit) == 0x0000EC, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_LineTraceSingle_ReturnValue) == 0x000178, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_bBlockingHit) == 0x000179, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_bInitialOverlap) == 0x00017A, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_Time) == 0x00017C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_Distance) == 0x000180, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_Location) == 0x000184, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_ImpactPoint) == 0x000190, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_Normal) == 0x00019C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_ImpactNormal) == 0x0001A8, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_PhysMat) == 0x0001B8, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_HitActor) == 0x0001C0, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_HitComponent) == 0x0001C8, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_HitBoneName) == 0x0001D0, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_HitItem) == 0x0001D8, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_ElementIndex) == 0x0001DC, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_FaceIndex) == 0x0001E0, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_TraceStart) == 0x0001E4, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_BreakHitResult_TraceEnd) == 0x0001F0, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, K2Node_Select_Default) == 0x0001FC, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath, CallFunc_Add_VectorVector_ReturnValue_1) == 0x000208, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_FindHammerPath::CallFunc_Add_VectorVector_ReturnValue_1' has a wrong offset!");

// Function GA_HighTower_Tapas_SkyStrike_Fire.GA_HighTower_Tapas_SkyStrike_Fire_C.GetAimedAtPoint
// 0x03A0 (0x03A0 - 0x0000)
struct GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint final
{
public:
	struct FVector                                OutHit_Location;                                   // 0x0000(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                WaterHit;                                          // 0x000C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         WaterDistance;                                     // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HitWater;                                          // 0x001C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          HitSomething;                                      // 0x001D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E[0x2];                                       // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x0020(0x0010)(ConstParm, ReferenceParm, HasGetValueTypeHash)
	struct FGameplayAbilityActorInfo              CallFunc_GetActorInfo_ReturnValue;                 // 0x0030(0x0048)(ContainsInstancedReference)
	float                                         CallFunc_GetValueAtLevel_ReturnValue;              // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x007C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityActorInfo              CallFunc_GetActorInfo_ReturnValue_1;               // 0x0088(0x0048)(ContainsInstancedReference)
	float                                         CallFunc_BreakVector_X;                            // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_MakeArray_Array;                            // 0x00E0(0x0010)(ConstParm, ReferenceParm, HasGetValueTypeHash)
	float                                         CallFunc_SelectFloat_ReturnValue;                  // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F4[0x4];                                       // 0x00F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerPawn*                        K2Node_DynamicCast_AsFort_Player_Pawn;             // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerController*                  CallFunc_GetFortPlayerControllerFromActor_ReturnValue; // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetCameraLocation_ReturnValue;            // 0x0110(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_GetCameraRotation_ReturnValue;            // 0x011C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_GetForwardVector_ReturnValue;             // 0x0128(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0134(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0140(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingleByProfile_OutHit;          // 0x014C(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingleByProfile_ReturnValue;     // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x01D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x01DA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1DB[0x1];                                      // 0x01DB(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x01DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x01E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x01E4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x01F0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x01FC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0208(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_214[0x4];                                      // 0x0214(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0218(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0228(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0230(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0238(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x023C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0240(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0244(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0250(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_SelectVector_ReturnValue;                 // 0x025C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue_1;           // 0x0268(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_X_1;                          // 0x0274(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y_1;                          // 0x0278(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z_1;                          // 0x027C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0280(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x028C(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x0318(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit_1;            // 0x0319(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap_1;         // 0x031A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31B[0x1];                                      // 0x031B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time_1;                    // 0x031C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance_1;                // 0x0320(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location_1;                // 0x0324(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint_1;             // 0x0330(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal_1;                  // 0x033C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal_1;            // 0x0348(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_354[0x4];                                      // 0x0354(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat_1;                 // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor_1;                // 0x0360(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent_1;            // 0x0368(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName_1;             // 0x0370(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem_1;                 // 0x0378(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex_1;            // 0x037C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex_1;               // 0x0380(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart_1;              // 0x0384(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd_1;                // 0x0390(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint) == 0x000008, "Wrong alignment on GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint");
static_assert(sizeof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint) == 0x0003A0, "Wrong size on GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, OutHit_Location) == 0x000000, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::OutHit_Location' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, WaterHit) == 0x00000C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::WaterHit' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, WaterDistance) == 0x000018, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::WaterDistance' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, HitWater) == 0x00001C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::HitWater' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, HitSomething) == 0x00001D, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::HitSomething' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, Temp_object_Variable) == 0x000020, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_GetActorInfo_ReturnValue) == 0x000030, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_GetActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_GetValueAtLevel_ReturnValue) == 0x000078, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_GetValueAtLevel_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_K2_GetActorLocation_ReturnValue) == 0x00007C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_GetActorInfo_ReturnValue_1) == 0x000088, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_GetActorInfo_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakVector_X) == 0x0000D0, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakVector_Y) == 0x0000D4, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakVector_Z) == 0x0000D8, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x0000DC, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, K2Node_MakeArray_Array) == 0x0000E0, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_SelectFloat_ReturnValue) == 0x0000F0, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, K2Node_DynamicCast_AsFort_Player_Pawn) == 0x0000F8, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::K2Node_DynamicCast_AsFort_Player_Pawn' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, K2Node_DynamicCast_bSuccess) == 0x000100, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_GetFortPlayerControllerFromActor_ReturnValue) == 0x000108, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_GetFortPlayerControllerFromActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_GetCameraLocation_ReturnValue) == 0x000110, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_GetCameraLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_GetCameraRotation_ReturnValue) == 0x00011C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_GetCameraRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_GetForwardVector_ReturnValue) == 0x000128, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_GetForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000134, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_Add_VectorVector_ReturnValue) == 0x000140, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_LineTraceSingleByProfile_OutHit) == 0x00014C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_LineTraceSingleByProfile_OutHit' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_LineTraceSingleByProfile_ReturnValue) == 0x0001D8, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_LineTraceSingleByProfile_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_bBlockingHit) == 0x0001D9, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_bInitialOverlap) == 0x0001DA, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_Time) == 0x0001DC, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_Distance) == 0x0001E0, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_Location) == 0x0001E4, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_ImpactPoint) == 0x0001F0, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_Normal) == 0x0001FC, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_ImpactNormal) == 0x000208, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_PhysMat) == 0x000218, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_HitActor) == 0x000220, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_HitComponent) == 0x000228, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_HitBoneName) == 0x000230, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_HitItem) == 0x000238, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_ElementIndex) == 0x00023C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_FaceIndex) == 0x000240, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_TraceStart) == 0x000244, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_TraceEnd) == 0x000250, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_SelectVector_ReturnValue) == 0x00025C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_SelectVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_Add_VectorVector_ReturnValue_1) == 0x000268, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_Add_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakVector_X_1) == 0x000274, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakVector_Y_1) == 0x000278, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakVector_Z_1) == 0x00027C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_MakeVector_ReturnValue) == 0x000280, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_LineTraceSingle_OutHit) == 0x00028C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_LineTraceSingle_ReturnValue) == 0x000318, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_bBlockingHit_1) == 0x000319, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_bBlockingHit_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_bInitialOverlap_1) == 0x00031A, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_bInitialOverlap_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_Time_1) == 0x00031C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_Time_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_Distance_1) == 0x000320, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_Distance_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_Location_1) == 0x000324, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_Location_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_ImpactPoint_1) == 0x000330, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_ImpactPoint_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_Normal_1) == 0x00033C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_Normal_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_ImpactNormal_1) == 0x000348, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_ImpactNormal_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_PhysMat_1) == 0x000358, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_PhysMat_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_HitActor_1) == 0x000360, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_HitActor_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_HitComponent_1) == 0x000368, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_HitComponent_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_HitBoneName_1) == 0x000370, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_HitBoneName_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_HitItem_1) == 0x000378, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_HitItem_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_ElementIndex_1) == 0x00037C, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_ElementIndex_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_FaceIndex_1) == 0x000380, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_FaceIndex_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_TraceStart_1) == 0x000384, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_TraceStart_1' has a wrong offset!");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint, CallFunc_BreakHitResult_TraceEnd_1) == 0x000390, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_GetAimedAtPoint::CallFunc_BreakHitResult_TraceEnd_1' has a wrong offset!");

// Function GA_HighTower_Tapas_SkyStrike_Fire.GA_HighTower_Tapas_SkyStrike_Fire_C.SetHover
// 0x0001 (0x0001 - 0x0000)
struct GA_HighTower_Tapas_SkyStrike_Fire_C_SetHover final
{
public:
	bool                                          On;                                                // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_HighTower_Tapas_SkyStrike_Fire_C_SetHover) == 0x000001, "Wrong alignment on GA_HighTower_Tapas_SkyStrike_Fire_C_SetHover");
static_assert(sizeof(GA_HighTower_Tapas_SkyStrike_Fire_C_SetHover) == 0x000001, "Wrong size on GA_HighTower_Tapas_SkyStrike_Fire_C_SetHover");
static_assert(offsetof(GA_HighTower_Tapas_SkyStrike_Fire_C_SetHover, On) == 0x000000, "Member 'GA_HighTower_Tapas_SkyStrike_Fire_C_SetHover::On' has a wrong offset!");

}

