#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Hightower_HoneyDew_Fist_Mantis

#include "Basic.hpp"

#include "GA_Melee_Mantis_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Hightower_HoneyDew_Fist_Mantis.GA_Hightower_HoneyDew_Fist_Mantis_C
// 0x0000 (0x0AF8 - 0x0AF8)
class UGA_Hightower_HoneyDew_Fist_Mantis_C final : public UGA_Melee_Mantis_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Hightower_HoneyDew_Fist_Mantis_C">();
	}
	static class UGA_Hightower_HoneyDew_Fist_Mantis_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Hightower_HoneyDew_Fist_Mantis_C>();
	}
};
static_assert(alignof(UGA_Hightower_HoneyDew_Fist_Mantis_C) == 0x000008, "Wrong alignment on UGA_Hightower_HoneyDew_Fist_Mantis_C");
static_assert(sizeof(UGA_Hightower_HoneyDew_Fist_Mantis_C) == 0x000AF8, "Wrong size on UGA_Hightower_HoneyDew_Fist_Mantis_C");

}

