#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Athena_Knockback_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp.GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C
// 0x0008 (0x0CC8 - 0x0CC0)
class UGA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C final : public UGA_Athena_Knockback_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C; // 0x0CC0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp(int32 EntryPoint);
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C">();
	}
	static class UGA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C>();
	}
};
static_assert(alignof(UGA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C) == 0x000008, "Wrong alignment on UGA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C");
static_assert(sizeof(UGA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C) == 0x000CC8, "Wrong size on UGA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C");
static_assert(offsetof(UGA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C, UberGraphFrame_GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C) == 0x000CC0, "Member 'UGA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C::UberGraphFrame_GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C' has a wrong offset!");

}

