#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_PreventJump

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_PreventJump.GA_PreventJump_C
// 0x0008 (0x0AB0 - 0x0AA8)
class UGA_PreventJump_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AA8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_PreventJump(int32 EntryPoint);
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_PreventJump_C">();
	}
	static class UGA_PreventJump_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_PreventJump_C>();
	}
};
static_assert(alignof(UGA_PreventJump_C) == 0x000008, "Wrong alignment on UGA_PreventJump_C");
static_assert(sizeof(UGA_PreventJump_C) == 0x000AB0, "Wrong size on UGA_PreventJump_C");
static_assert(offsetof(UGA_PreventJump_C, UberGraphFrame) == 0x000AA8, "Member 'UGA_PreventJump_C::UberGraphFrame' has a wrong offset!");

}

