#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Trap_FrostedTips_Wall

#include "Basic.hpp"

#include "GA_Trap_FrostedTips_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Trap_FrostedTips_Wall.GA_Trap_FrostedTips_Wall_C
// 0x0000 (0x0C58 - 0x0C58)
class UGA_Trap_FrostedTips_Wall_C final : public UGA_Trap_FrostedTips_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Trap_FrostedTips_Wall_C">();
	}
	static class UGA_Trap_FrostedTips_Wall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Trap_FrostedTips_Wall_C>();
	}
};
static_assert(alignof(UGA_Trap_FrostedTips_Wall_C) == 0x000008, "Wrong alignment on UGA_Trap_FrostedTips_Wall_C");
static_assert(sizeof(UGA_Trap_FrostedTips_Wall_C) == 0x000C58, "Wrong size on UGA_Trap_FrostedTips_Wall_C");

}

