#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_HighTower_Wasabi_Claws_SpinSlash_Hit

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function GCN_HighTower_Wasabi_Claws_SpinSlash_Hit.GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C.OnBurst
// 0x0388 (0x0388 - 0x0000)
struct GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UParticleSystemComponent*>       ParticleComponents;                                // 0x00C0(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
	TArray<class UAudioComponent*>                AudioComponents;                                   // 0x00D0(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
	class UMatineeCameraShake*                    BurstCameraShakeInstance;                          // 0x00E0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ADecalActor*                            BurstDecalInstance;                                // 0x00E8(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 LocalHitActor;                                     // 0x00F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                LocalImpactLocation;                               // 0x00F8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakGameplayCueParameters_NormalizedMagnitude; // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakGameplayCueParameters_RawMagnitude;  // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10C[0x4];                                      // 0x010C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEffectContextHandle           CallFunc_BreakGameplayCueParameters_EffectContext; // 0x0110(0x0018)()
	struct FGameplayTag                           CallFunc_BreakGameplayCueParameters_MatchedTagName; // 0x0128(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           CallFunc_BreakGameplayCueParameters_OriginalTag;   // 0x0130(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  CallFunc_BreakGameplayCueParameters_AggregatedSourceTags; // 0x0138(0x0020)()
	struct FGameplayTagContainer                  CallFunc_BreakGameplayCueParameters_AggregatedTargetTags; // 0x0158(0x0020)()
	struct FVector                                CallFunc_BreakGameplayCueParameters_Location;      // 0x0178(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakGameplayCueParameters_Normal;        // 0x0184(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakGameplayCueParameters_Instigator;    // 0x0190(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakGameplayCueParameters_EffectCauser;  // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_BreakGameplayCueParameters_SourceObject;  // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakGameplayCueParameters_PhysicalMaterial; // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakGameplayCueParameters_GameplayEffectLevel; // 0x01B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakGameplayCueParameters_AbilityLevel;  // 0x01B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        CallFunc_BreakGameplayCueParameters_TargetAttachComponent; // 0x01B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_EffectContextGetEffectCauser_ReturnValue; // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_EffectContextGetHitResult_ReturnValue;    // 0x01C8(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         Pad_254[0x4];                                      // 0x0254(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortWeapon*                            K2Node_DynamicCast_AsFort_Weapon;                  // 0x0258(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0260(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0261(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0262(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_263[0x1];                                      // 0x0263(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0264(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0268(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x026C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0278(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0284(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0290(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29C[0x4];                                      // 0x029C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x02A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x02B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x02B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x02C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x02C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x02C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x02CC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x02D8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2E4[0x4];                                      // 0x02E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x02E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetActorForwardVector_ReturnValue;        // 0x02F0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x02FC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0308(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_FindLookAtRotation_ReturnValue;           // 0x0314(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Normal_ReturnValue;                       // 0x0320(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x032C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x0330(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x0334(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Dot_VectorVector_ReturnValue;             // 0x0338(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33C[0x4];                                      // 0x033C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IFortVehicleInterface> K2Node_DynamicCast_AsFort_Vehicle_Interface;       // 0x0340(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0350(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_351[0x3];                                      // 0x0351(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0354(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPawn*                              K2Node_DynamicCast_AsFort_Pawn;                    // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0360(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_361[0x3];                                      // 0x0361(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0364(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0368(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_374[0x4];                                      // 0x0374(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UDecalComponent*                        CallFunc_SpawnDecalAtLocation_ReturnValue;         // 0x0378(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFXSystemComponent*                     CallFunc_SpawnFXAtLocation_ReturnValue;            // 0x0380(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst) == 0x000008, "Wrong alignment on GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst");
static_assert(sizeof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst) == 0x000388, "Wrong size on GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, MyTarget) == 0x000000, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::MyTarget' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, Parameters) == 0x000008, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::Parameters' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, ParticleComponents) == 0x0000C0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::ParticleComponents' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, AudioComponents) == 0x0000D0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::AudioComponents' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, BurstCameraShakeInstance) == 0x0000E0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::BurstCameraShakeInstance' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, BurstDecalInstance) == 0x0000E8, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::BurstDecalInstance' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, LocalHitActor) == 0x0000F0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::LocalHitActor' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, LocalImpactLocation) == 0x0000F8, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::LocalImpactLocation' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_NormalizedMagnitude) == 0x000104, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_NormalizedMagnitude' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_RawMagnitude) == 0x000108, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_RawMagnitude' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_EffectContext) == 0x000110, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_EffectContext' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_MatchedTagName) == 0x000128, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_MatchedTagName' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_OriginalTag) == 0x000130, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_OriginalTag' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_AggregatedSourceTags) == 0x000138, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_AggregatedSourceTags' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_AggregatedTargetTags) == 0x000158, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_AggregatedTargetTags' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_Location) == 0x000178, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_Location' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_Normal) == 0x000184, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_Normal' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_Instigator) == 0x000190, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_Instigator' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_EffectCauser) == 0x000198, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_EffectCauser' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_SourceObject) == 0x0001A0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_SourceObject' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_PhysicalMaterial) == 0x0001A8, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_PhysicalMaterial' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_GameplayEffectLevel) == 0x0001B0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_GameplayEffectLevel' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_AbilityLevel) == 0x0001B4, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_AbilityLevel' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakGameplayCueParameters_TargetAttachComponent) == 0x0001B8, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakGameplayCueParameters_TargetAttachComponent' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_EffectContextGetEffectCauser_ReturnValue) == 0x0001C0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_EffectContextGetEffectCauser_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_EffectContextGetHitResult_ReturnValue) == 0x0001C8, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_EffectContextGetHitResult_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, K2Node_DynamicCast_AsFort_Weapon) == 0x000258, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::K2Node_DynamicCast_AsFort_Weapon' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, K2Node_DynamicCast_bSuccess) == 0x000260, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_bBlockingHit) == 0x000261, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_bInitialOverlap) == 0x000262, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_Time) == 0x000264, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_Distance) == 0x000268, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_Location) == 0x00026C, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_ImpactPoint) == 0x000278, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_Normal) == 0x000284, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_ImpactNormal) == 0x000290, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_PhysMat) == 0x0002A0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_HitActor) == 0x0002A8, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_HitComponent) == 0x0002B0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_HitBoneName) == 0x0002B8, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_HitItem) == 0x0002C0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_ElementIndex) == 0x0002C4, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_FaceIndex) == 0x0002C8, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_TraceStart) == 0x0002CC, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakHitResult_TraceEnd) == 0x0002D8, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_GetOwner_ReturnValue) == 0x0002E8, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_GetActorForwardVector_ReturnValue) == 0x0002F0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_GetActorForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0002FC, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000308, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_FindLookAtRotation_ReturnValue) == 0x000314, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_FindLookAtRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_Normal_ReturnValue) == 0x000320, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_Normal_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakRotator_Roll) == 0x00032C, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakRotator_Pitch) == 0x000330, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_BreakRotator_Yaw) == 0x000334, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_Dot_VectorVector_ReturnValue) == 0x000338, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_Dot_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, K2Node_DynamicCast_AsFort_Vehicle_Interface) == 0x000340, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::K2Node_DynamicCast_AsFort_Vehicle_Interface' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, K2Node_DynamicCast_bSuccess_1) == 0x000350, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000354, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, K2Node_DynamicCast_AsFort_Pawn) == 0x000358, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::K2Node_DynamicCast_AsFort_Pawn' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, K2Node_DynamicCast_bSuccess_2) == 0x000360, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_Add_FloatFloat_ReturnValue) == 0x000364, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_MakeRotator_ReturnValue) == 0x000368, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_SpawnDecalAtLocation_ReturnValue) == 0x000378, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_SpawnDecalAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst, CallFunc_SpawnFXAtLocation_ReturnValue) == 0x000380, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurst::CallFunc_SpawnFXAtLocation_ReturnValue' has a wrong offset!");

// Function GCN_HighTower_Wasabi_Claws_SpinSlash_Hit.GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C.OnBurstNiagara
// 0x00F0 (0x00F0 - 0x0000)
struct GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UNiagaraComponent*>              ParticleComponents;                                // 0x00C0(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
	TArray<class UAudioComponent*>                AudioComponents;                                   // 0x00D0(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
	class UMatineeCameraShake*                    BurstCameraShakeInstance;                          // 0x00E0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ADecalActor*                            BurstDecalInstance;                                // 0x00E8(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara) == 0x000008, "Wrong alignment on GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara");
static_assert(sizeof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara) == 0x0000F0, "Wrong size on GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara, MyTarget) == 0x000000, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara::MyTarget' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara, Parameters) == 0x000008, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara::Parameters' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara, ParticleComponents) == 0x0000C0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara::ParticleComponents' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara, AudioComponents) == 0x0000D0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara::AudioComponents' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara, BurstCameraShakeInstance) == 0x0000E0, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara::BurstCameraShakeInstance' has a wrong offset!");
static_assert(offsetof(GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara, BurstDecalInstance) == 0x0000E8, "Member 'GCN_HighTower_Wasabi_Claws_SpinSlash_Hit_C_OnBurstNiagara::BurstDecalInstance' has a wrong offset!");

}

