#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Awakening_HightowerDate

#include "Basic.hpp"

#include "GE_Quest_TagCarrier_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Awakening_HightowerDate.GE_Awakening_HightowerDate_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_Awakening_HightowerDate_C final : public UGE_Quest_TagCarrier_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Awakening_HightowerDate_C">();
	}
	static class UGE_Awakening_HightowerDate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Awakening_HightowerDate_C>();
	}
};
static_assert(alignof(UGE_Awakening_HightowerDate_C) == 0x000008, "Wrong alignment on UGE_Awakening_HightowerDate_C");
static_assert(sizeof(UGE_Awakening_HightowerDate_C) == 0x0007B8, "Wrong size on UGE_Awakening_HightowerDate_C");

}

