#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_HighTower_Date_BallLightning_ExplodePawns

#include "Basic.hpp"

#include "GET_DirectPhysicalDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HighTower_Date_BallLightning_ExplodePawns.GE_HighTower_Date_BallLightning_ExplodePawns_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_HighTower_Date_BallLightning_ExplodePawns_C final : public UGET_DirectPhysicalDamage_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_HighTower_Date_BallLightning_ExplodePawns_C">();
	}
	static class UGE_HighTower_Date_BallLightning_ExplodePawns_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HighTower_Date_BallLightning_ExplodePawns_C>();
	}
};
static_assert(alignof(UGE_HighTower_Date_BallLightning_ExplodePawns_C) == 0x000008, "Wrong alignment on UGE_HighTower_Date_BallLightning_ExplodePawns_C");
static_assert(sizeof(UGE_HighTower_Date_BallLightning_ExplodePawns_C) == 0x0007B8, "Wrong size on UGE_HighTower_Date_BallLightning_ExplodePawns_C");

}

