#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HighTower_Date_LayerAnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "HighTowerRuntime_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass HighTower_Date_LayerAnimBP.HighTower_Date_LayerAnimBP_C
// 0x2780 (0x2A80 - 0x0300)
class UHighTower_Date_LayerAnimBP_C final : public UFortItemLayerAnimInstance_DateGaunlets
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0300(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimInstanceSubsystemData             AnimBlueprintClassSubsystem_PropertyAccess;        // 0x0308(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_309[0x7];                                      // 0x0309(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_Root                         AnimGraphNode_Root_34;                             // 0x0310(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_18;                  // 0x0340(0x0088)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x03C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x03F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x0418(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x0440(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x0468(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x0490(0x0028)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_4;                  // 0x04B8(0x00E0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_9;                   // 0x0598(0x00A0)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_3;                  // 0x0638(0x00E0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_8;                   // 0x0718(0x00A0)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_2;                  // 0x07B8(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x0898(0x0030)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_1;                  // 0x08C8(0x00E0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_7;                   // 0x09A8(0x00A0)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x0A48(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x0B28(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x0B58(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x0B80(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x0BB0(0x00B0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x0C60(0x00C8)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace;            // 0x0D28(0x0188)()
	struct FAnimNode_Root                         AnimGraphNode_Root_33;                             // 0x0EB0(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_17;                  // 0x0EE0(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_32;                             // 0x0F68(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_16;                  // 0x0F98(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_31;                             // 0x1020(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_30;                             // 0x1050(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_29;                             // 0x1080(0x0030)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_6;                   // 0x10B0(0x00A0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x1150(0x0078)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x11C8(0x0078)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x1240(0x0078)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_5;                   // 0x12B8(0x00A0)()
	struct FAnimNode_Root                         AnimGraphNode_Root_28;                             // 0x1358(0x0030)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_4;                   // 0x1388(0x00A0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x1428(0x0078)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x14A0(0x0078)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x1518(0x0078)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_3;                   // 0x1590(0x00A0)()
	struct FAnimNode_Root                         AnimGraphNode_Root_27;                             // 0x1630(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x1660(0x0078)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_2;                   // 0x16D8(0x00A0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x1778(0x0078)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x17F0(0x0078)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1;                   // 0x1868(0x00A0)()
	struct FAnimNode_Root                         AnimGraphNode_Root_26;                             // 0x1908(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x1938(0x0078)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x19B0(0x0078)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x1A28(0x00A0)()
	struct FAnimNode_Root                         AnimGraphNode_Root_25;                             // 0x1AC8(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_24;                             // 0x1AF8(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_23;                             // 0x1B28(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_22;                             // 0x1B58(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_21;                             // 0x1B88(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_20;                             // 0x1BB8(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_15;                  // 0x1BE8(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_19;                             // 0x1C70(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_14;                  // 0x1CA0(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_18;                             // 0x1D28(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_13;                  // 0x1D58(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_17;                             // 0x1DE0(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_12;                  // 0x1E10(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_16;                             // 0x1E98(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_11;                  // 0x1EC8(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_15;                             // 0x1F50(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_10;                  // 0x1F80(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_14;                             // 0x2008(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_9;                   // 0x2038(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_13;                             // 0x20C0(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_8;                   // 0x20F0(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_12;                             // 0x2178(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_7;                   // 0x21A8(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_11;                             // 0x2230(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_6;                   // 0x2260(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_10;                             // 0x22E8(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_5;                   // 0x2318(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_9;                              // 0x23A0(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_8;                              // 0x23D0(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_7;                              // 0x2400(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_6;                              // 0x2430(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_5;                              // 0x2460(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_4;                              // 0x2490(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_4;                   // 0x24C0(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_3;                              // 0x2548(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_3;                   // 0x2578(0x0088)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_2;                   // 0x2600(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x2688(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_1;                   // 0x26B8(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x2740(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x2770(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x27F8(0x0030)()
	struct FFortAnimInput_AdjustedAim             InputParam;                                        // 0x2828(0x0240)(BlueprintReadOnly, NoDestructor)
	bool                                          IsFiringLeft;                                      // 0x2A68(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsFiringRight;                                     // 0x2A69(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A6A[0x2];                                     // 0x2A6A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ResultingPitch;                                    // 0x2A6C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsInAir;                                           // 0x2A70(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bIsBoostJumping_b;                                 // 0x2A71(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsTargeting;                                       // 0x2A72(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bIsDBNOCarrying;                                   // 0x2A73(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         FallPlayRate;                                      // 0x2A74(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShouldPlayCustomJumpLand;                          // 0x2A78(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_HighTower_Date_LayerAnimBP(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void ItemPreIK(const struct FPoseLink& InPose_PreIK, struct FPoseLink* ItemPreIK_0);
	void ItemFullBodyOverride(const struct FPoseLink& InPoseFullBody, struct FPoseLink* ItemFullBodyOverride_0);
	void ItemAimOffset(const struct FPoseLink& InPose_AimOffset, float AimOffsetAlpha, float Yaw, float Pitch, const struct FPoseLink& InPose_UpperLowerPreMeleeAO, struct FPoseLink* ItemAimOffset_0);
	void ItemSkeletalControl(const struct FPoseLink& InPose, struct FPoseLink* ItemSkeletalControl_0);
	void ItemSwimJumpSurfaceEnd(struct FPoseLink* ItemSwimJumpSurfaceEnd_0);
	void ItemSwimJumpSurfaceLoop(struct FPoseLink* ItemSwimJumpSurfaceLoop_0);
	void ItemSwimJumpFallLoop(struct FPoseLink* ItemSwimJumpFallLoop_0);
	void ItemSwimJumpStartLoop(struct FPoseLink* ItemSwimJumpStartLoop_0);
	void ItemSwimJumpStart(struct FPoseLink* ItemSwimJumpStart_0);
	void ItemRelaxedEntry(const struct FPoseLink& InPoseRelaxedEntry, struct FPoseLink* ItemRelaxedEntry_0);
	void ItemLowerBodyJogPostPivot(const struct FPoseLink& InPoseLowerBodyJogPostPivot, struct FPoseLink* ItemLowerBodyJogPostPivot_0);
	void ItemLowerBodyJogPrePivot(const struct FPoseLink& InPoseLowerBodyJogPrePivot, struct FPoseLink* ItemLowerBodyJogPrePivot_0);
	void ItemLowerBodyJogStop(const struct FPoseLink& InPoseLowerBodyJogStop, struct FPoseLink* ItemLowerBodyJogStop_0);
	void ItemLowerBodyJogStart(const struct FPoseLink& InPoseLowerBodyJogStart, struct FPoseLink* ItemLowerBodyJogStart_0);
	void ItemLowerBodyLeanAdditive(const struct FPoseLink& InPoseLowerBodyLeanAdditive, struct FPoseLink* ItemLowerBodyLeanAdditive_0);
	void ItemLowerBodyMovement(const struct FPoseLink& InPoseLowerBodyMovement, struct FPoseLink* ItemLowerBodyMovement_0);
	void ItemJogPostPivotAdditive(const struct FPoseLink& InPosePostPivotAdditive, struct FPoseLink* ItemJogPostPivotAdditive_0);
	void ItemJogPrePivotAdditive(const struct FPoseLink& InPosePrePivotAdditive, struct FPoseLink* ItemJogPrePivotAdditive_0);
	void ItemJogStopAdditive(const struct FPoseLink& InPoseJogStopAdditive, struct FPoseLink* ItemJogStopAdditive_0);
	void ItemJogStartAdditive(const struct FPoseLink& InPoseJogStartAdditive, struct FPoseLink* ItemJogStartAdditive_0);
	void ItemFlyModeLoopAdditive(struct FPoseLink* ItemFlyModeLoopAdditive_0);
	void ItemFlyModeStartAdditive(struct FPoseLink* ItemFlyModeStartAdditive_0);
	void ItemZipLineStartAdditive(struct FPoseLink* ItemZipLineStartAdditive_0);
	void ItemJetPackJumpAdditive(struct FPoseLink* ItemJetPackJumpAdditive_0);
	void ItemJetPackStartAdditive(struct FPoseLink* ItemJetPackStartAdditive_0);
	void ItemFallLandAdditive(struct FPoseLink* ItemFallLandAdditive_0);
	void ItemFallAdditive(struct FPoseLink* ItemFallAdditive_0);
	void ItemJumpLoopAdditive(struct FPoseLink* ItemJumpLoopAdditive_0);
	void ItemJumpUpAdditive(struct FPoseLink* ItemJumpUpAdditive_0);
	void ItemSlopeSliding(struct FPoseLink* ItemSlopeSliding_0);
	void ItemCrouchTurningAdditive(struct FPoseLink* ItemCrouchTurningAdditive_0);
	void ItemIdleAdditive(const struct FPoseLink& InPoseIdleAdditive, struct FPoseLink* ItemIdleAdditive_0);
	void ItemFullBodySprint(const struct FPoseLink& InPoseSprint, struct FPoseLink* ItemFullBodySprint_0);
	void ItemUpperBody(const struct FPoseLink& InPoseUpperBody, const struct FFortAnimInput_AdjustedAim& InputParam_0, struct FPoseLink* ItemUpperBody_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HighTower_Date_LayerAnimBP_C">();
	}
	static class UHighTower_Date_LayerAnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHighTower_Date_LayerAnimBP_C>();
	}
};
static_assert(alignof(UHighTower_Date_LayerAnimBP_C) == 0x000010, "Wrong alignment on UHighTower_Date_LayerAnimBP_C");
static_assert(sizeof(UHighTower_Date_LayerAnimBP_C) == 0x002A80, "Wrong size on UHighTower_Date_LayerAnimBP_C");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, UberGraphFrame) == 0x000300, "Member 'UHighTower_Date_LayerAnimBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimBlueprintClassSubsystem_PropertyAccess) == 0x000308, "Member 'UHighTower_Date_LayerAnimBP_C::AnimBlueprintClassSubsystem_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_34) == 0x000310, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_34' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_18) == 0x000340, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_18' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_TransitionResult_5) == 0x0003C8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_TransitionResult_4) == 0x0003F0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_TransitionResult_3) == 0x000418, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_TransitionResult_2) == 0x000440, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_TransitionResult_1) == 0x000468, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_TransitionResult) == 0x000490, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendSpacePlayer_4) == 0x0004B8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendSpacePlayer_4' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendListByBool_9) == 0x000598, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendListByBool_9' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendSpacePlayer_3) == 0x000638, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendSpacePlayer_3' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendListByBool_8) == 0x000718, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendListByBool_8' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendSpacePlayer_2) == 0x0007B8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendSpacePlayer_2' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_StateResult_2) == 0x000898, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendSpacePlayer_1) == 0x0008C8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendSpacePlayer_1' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendListByBool_7) == 0x0009A8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendListByBool_7' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendSpacePlayer) == 0x000A48, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendSpacePlayer' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_StateResult_1) == 0x000B28, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_UseCachedPose) == 0x000B58, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_StateResult) == 0x000B80, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_StateMachine) == 0x000BB0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_SaveCachedPose) == 0x000C60, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_RotationOffsetBlendSpace) == 0x000D28, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_RotationOffsetBlendSpace' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_33) == 0x000EB0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_33' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_17) == 0x000EE0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_17' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_32) == 0x000F68, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_32' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_16) == 0x000F98, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_16' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_31) == 0x001020, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_31' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_30) == 0x001050, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_30' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_29) == 0x001080, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_29' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendListByBool_6) == 0x0010B0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendListByBool_6' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_SequencePlayer_10) == 0x001150, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_SequencePlayer_10' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_SequencePlayer_9) == 0x0011C8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_SequencePlayer_9' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_SequencePlayer_8) == 0x001240, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_SequencePlayer_8' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendListByBool_5) == 0x0012B8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendListByBool_5' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_28) == 0x001358, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_28' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendListByBool_4) == 0x001388, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendListByBool_4' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_SequencePlayer_7) == 0x001428, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_SequencePlayer_7' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_SequencePlayer_6) == 0x0014A0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_SequencePlayer_6' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_SequencePlayer_5) == 0x001518, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendListByBool_3) == 0x001590, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendListByBool_3' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_27) == 0x001630, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_27' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_SequencePlayer_4) == 0x001660, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendListByBool_2) == 0x0016D8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendListByBool_2' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_SequencePlayer_3) == 0x001778, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_SequencePlayer_2) == 0x0017F0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendListByBool_1) == 0x001868, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendListByBool_1' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_26) == 0x001908, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_26' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_SequencePlayer_1) == 0x001938, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_SequencePlayer) == 0x0019B0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_BlendListByBool) == 0x001A28, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_25) == 0x001AC8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_25' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_24) == 0x001AF8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_24' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_23) == 0x001B28, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_23' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_22) == 0x001B58, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_22' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_21) == 0x001B88, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_21' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_20) == 0x001BB8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_20' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_15) == 0x001BE8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_15' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_19) == 0x001C70, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_19' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_14) == 0x001CA0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_14' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_18) == 0x001D28, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_18' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_13) == 0x001D58, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_13' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_17) == 0x001DE0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_17' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_12) == 0x001E10, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_12' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_16) == 0x001E98, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_16' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_11) == 0x001EC8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_11' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_15) == 0x001F50, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_15' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_10) == 0x001F80, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_10' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_14) == 0x002008, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_14' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_9) == 0x002038, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_9' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_13) == 0x0020C0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_13' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_8) == 0x0020F0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_8' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_12) == 0x002178, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_12' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_7) == 0x0021A8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_7' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_11) == 0x002230, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_11' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_6) == 0x002260, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_6' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_10) == 0x0022E8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_10' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_5) == 0x002318, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_5' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_9) == 0x0023A0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_9' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_8) == 0x0023D0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_8' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_7) == 0x002400, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_7' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_6) == 0x002430, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_6' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_5) == 0x002460, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_5' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_4) == 0x002490, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_4' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_4) == 0x0024C0, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_4' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_3) == 0x002548, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_3' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_3) == 0x002578, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_3' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_2) == 0x002600, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_2' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_2) == 0x002688, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_2' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose_1) == 0x0026B8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose_1' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root_1) == 0x002740, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root_1' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_LinkedInputPose) == 0x002770, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, AnimGraphNode_Root) == 0x0027F8, "Member 'UHighTower_Date_LayerAnimBP_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, InputParam) == 0x002828, "Member 'UHighTower_Date_LayerAnimBP_C::InputParam' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, IsFiringLeft) == 0x002A68, "Member 'UHighTower_Date_LayerAnimBP_C::IsFiringLeft' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, IsFiringRight) == 0x002A69, "Member 'UHighTower_Date_LayerAnimBP_C::IsFiringRight' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, ResultingPitch) == 0x002A6C, "Member 'UHighTower_Date_LayerAnimBP_C::ResultingPitch' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, IsInAir) == 0x002A70, "Member 'UHighTower_Date_LayerAnimBP_C::IsInAir' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, bIsBoostJumping_b) == 0x002A71, "Member 'UHighTower_Date_LayerAnimBP_C::bIsBoostJumping_b' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, IsTargeting) == 0x002A72, "Member 'UHighTower_Date_LayerAnimBP_C::IsTargeting' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, bIsDBNOCarrying) == 0x002A73, "Member 'UHighTower_Date_LayerAnimBP_C::bIsDBNOCarrying' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, FallPlayRate) == 0x002A74, "Member 'UHighTower_Date_LayerAnimBP_C::FallPlayRate' has a wrong offset!");
static_assert(offsetof(UHighTower_Date_LayerAnimBP_C, ShouldPlayCustomJumpLand) == 0x002A78, "Member 'UHighTower_Date_LayerAnimBP_C::ShouldPlayCustomJumpLand' has a wrong offset!");

}

