#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LowTowerDataTracker

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LowTowerDataTracker.LowTowerDataTracker_C
// 0x0000 (0x01A8 - 0x01A8)
class ULowTowerDataTracker_C final : public UFortGameplayDataTrackerComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LowTowerDataTracker_C">();
	}
	static class ULowTowerDataTracker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULowTowerDataTracker_C>();
	}
};
static_assert(alignof(ULowTowerDataTracker_C) == 0x000008, "Wrong alignment on ULowTowerDataTracker_C");
static_assert(sizeof(ULowTowerDataTracker_C) == 0x0001A8, "Wrong size on ULowTowerDataTracker_C");

}

