#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Trap_Wall_FrostedTips

#include "Basic.hpp"

#include "Trap_Floor_FrostedTips_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Trap_Wall_FrostedTips.Trap_Wall_FrostedTips_C
// 0x0000 (0x0EB8 - 0x0EB8)
class ATrap_Wall_FrostedTips_C final : public ATrap_Floor_FrostedTips_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Trap_Wall_FrostedTips_C">();
	}
	static class ATrap_Wall_FrostedTips_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATrap_Wall_FrostedTips_C>();
	}
};
static_assert(alignof(ATrap_Wall_FrostedTips_C) == 0x000008, "Wrong alignment on ATrap_Wall_FrostedTips_C");
static_assert(sizeof(ATrap_Wall_FrostedTips_C) == 0x000EB8, "Wrong size on ATrap_Wall_FrostedTips_C");

}

